version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PihBCeaibkFLGyiigTaAxZgHlgvfRzwb
      MYSQL_DATABASE: railway
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm start"
    ports:
      - "7635:7635"
    environment:
      MYSQL_SERVER: monorail.proxy.rlwy.net
      MYSQL_USER: root
      MYSQL_PASSWORD: PihBCeaibkFLGyiigTaAxZgHlgvfRzwb
      MYSQL_DATABASE: railway
      PORT: 31536
    depends_on:
      - db
volumes:
  db_data:
